language: python

notifications:
  email: false

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install flake8
  - pip install coverage
  - pip install python-coveralls

# command to run tests
script: 
  - coverage run -m unittest discover
  - flake8 pluginmanager
  
after_success:
  - coverage report
  - coveralls
